### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by mikemfleming** [mikemfleming/spot-dawg#39]
When this issue is completed, the app will be ready to be published to Slack for other teams to use.

## Acceptance Criteria
- [x] Rename 
- [ ] Completes all Beta labelled tickets
- [ ] Completes all Beta - Security tickets 
- [ ] Completes all Beta - Testing tickets
- [ ] Completes all Beta - Feature tickets
