### ISSUE TITLE
Reorganize and add Tests

### ISSUE THREAD

**Issue by mikemfleming** [mikemfleming/spot-dawg#75]
- [ ] Set up and run
- [ ] Reacquaint with the codebase
- [ ] and auth workflow
- [ ] Add tests to for adding a song to the playlist
- [ ] test that it only adds once
